"""empty message

Revision ID: 9127b26ccfd8
Revises: 
Create Date: 2023-10-08 15:43:01.403507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9127b26ccfd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comentario_rep', sa.String(length=240), nullable=False))

    with op.batch_alter_table('comentarios_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comentario_rep', sa.String(length=240), nullable=False))

    with op.batch_alter_table('foro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comentario_rep', sa.String(length=240), nullable=False))

    with op.batch_alter_table('informacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comentario_rep', sa.String(length=240), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion', schema=None) as batch_op:
        batch_op.drop_column('comentario_rep')
        batch_op.drop_column('activo')

    with op.batch_alter_table('foro', schema=None) as batch_op:
        batch_op.drop_column('comentario_rep')
        batch_op.drop_column('activo')

    with op.batch_alter_table('comentarios_productos', schema=None) as batch_op:
        batch_op.drop_column('comentario_rep')
        batch_op.drop_column('activo')

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_column('comentario_rep')
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
