"""empty message

Revision ID: c01f2f046c63
Revises: 
Create Date: 2023-10-02 20:15:27.168944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01f2f046c63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
