"""empty message

Revision ID: d3ca1b211c2f
Revises: 
Create Date: 2023-10-01 22:19:07.304041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ca1b211c2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
