"""empty message

Revision ID: f7aea6d141f9
Revises: 
Create Date: 2023-10-08 17:12:45.883436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7aea6d141f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('comentario_rep',
               existing_type=mysql.VARCHAR(length=240),
               nullable=True)

    with op.batch_alter_table('comentarios_productos', schema=None) as batch_op:
        batch_op.alter_column('comentario_rep',
               existing_type=mysql.VARCHAR(length=240),
               nullable=True)

    with op.batch_alter_table('foro', schema=None) as batch_op:
        batch_op.alter_column('comentario_rep',
               existing_type=mysql.VARCHAR(length=240),
               nullable=True)

    with op.batch_alter_table('informacion', schema=None) as batch_op:
        batch_op.alter_column('comentario_rep',
               existing_type=mysql.VARCHAR(length=240),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion', schema=None) as batch_op:
        batch_op.alter_column('comentario_rep',
               existing_type=mysql.VARCHAR(length=240),
               nullable=False)

    with op.batch_alter_table('foro', schema=None) as batch_op:
        batch_op.alter_column('comentario_rep',
               existing_type=mysql.VARCHAR(length=240),
               nullable=False)

    with op.batch_alter_table('comentarios_productos', schema=None) as batch_op:
        batch_op.alter_column('comentario_rep',
               existing_type=mysql.VARCHAR(length=240),
               nullable=False)

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('comentario_rep',
               existing_type=mysql.VARCHAR(length=240),
               nullable=False)

    # ### end Alembic commands ###
